servicename: mynastyphpport
port: 8080
socketpath: /tmp/urocket.sock

openapi: pets-oas.yaml

paths:
  /get/pets:
    post:
      validatein: false
      inject:
        wd: /home/daniele/Development
        env:
          - MYENV=CI
        cmd: !ToSplit "/usr/bin/echo {{jsonpayload}}"
        channel: "cmdline"
        timeout: 300
        encoding: json
      logstdout: true
      validateout: false
  /get/cats:
    post:
      validatein: false
      inject:
        wd: /home/daniele/Development
        env:
          - MYENV=CI
        cmd: !Splitted ["/bin/sh","-c", "echo {{jsonpayload}} $REQUEST_ID"]
        channel: "cmdline"
        encoding: json
      logstdout: true
      validateout: false
#    post:
#      inject:
#        wd: /home/daniele/Documenti
#        env:
#          - MYENV=CI
#        urlparam-mode: true
#        encoding: json
#        cmd: /usr/bin/echo
#        channel: "cmdline"
