servicename: mynastyphpport
port: 8080
socketpath: /tmp/urocket.sock

openapi: pets-oas.yaml

paths:
  /get/pets:
    get:
      validatein: false
      inject:
        wd: /home/daniele/Development
        env:
          - MYENV=CI
        cmd: /usr/bin/echo
        channel: "cmdline"
        encoding: json
      logstdout: true
      validate-out: false
#    post:
#      inject:
#        wd: /home/daniele/Documenti
#        env:
#          - MYENV=CI
#        urlparam-mode: true
#        encoding: json
#        cmd: /usr/bin/echo
#        channel: "cmdline"
